### PR TITLE
Set disc and disctotal to 1

### PR DESCRIPTION
**Pull request by SenorSmartyPants**
Assume all audible media is not multi-disc. Better 1 than 0

Address parts of #2

### CODE REVIEW

**Comment by Neurrone** [comment]
Thanks for the PR.

I wasn't sure what the `medium` field does. Does this indicate the number of disks?

**Comment by SenorSmartyPants** [comment]
I did a little digging around in beets code and found this. So, yes, it seems that medium is the disc values.

https://github.com/beetbox/beets/blob/018396ccf74a35e56ab346ad390476a0e347307a/beets/autotag/__init__.py#L163-L165

**Review by Neurrone — CHANGES_REQUESTED** [review]
Could you also make the same change in `getAlbumFromYamlMetadata`? Around lines 203 and 215?

Its not ideal that I have this logic twice, pending a future refactor.

**Comment by SenorSmartyPants** [comment]
I left out the hard coded 1 values when reading from yaml so a user could set them to be anything they wanted.

**Review by Neurrone — APPROVED** [review]
LGTM

**Pull request merged**
